#! /usr/bin/env bash

set -eu

source "../site-content/tools.bash"

function render_date_dest_fs {
    TZ=UTC date "+%Y/%m/%d" -d "${1}"
}

function render_date {
    TZ=UTC date "+%d/%m/%Y" -d "${1}"
}

CONTENT_DIR=/usr/local/src/site-content/contents

ALL_CONTENTS="`ls -r ${CONTENT_DIR}`"

SITE_URL="https://diasbruno.github.io/articles"

function render_tag {
    local article_date="`render_date ${2}`"
    local date_path="`render_date_dest_fs "${2}"`"

    echo -e "[${article_date} - ${1}](${SITE_URL}/${date_path}/${3}.html)\n"
}

for content in $ALL_CONTENTS; do
    source "${CONTENT_DIR}/${content}/metadata.sh"

    [ "$STATUS" != "hidden" ] &&
	render_tag "${TITLE}" "${DATE}" "${SLUG}"
done
